citiLeaf/config/routes.rb
Rails.application.routes.draw do
	  devise_for :businesses
	  get 'home' => 'static_pages/home'

	  get 'about' => 'static_pages/about'

	  get 'cities' => 'static_pages/cities'

	  root "static_pages#home"
	end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 
	  get 'home' => 'static_pages/home'

	  get 'about' => 'static_pages/about'

	  get 'cities' => 'static_pages/cities'

	  root "static_pages#home"
	end
end

citiLeaf/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

citiLeaf/app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

citiLeaf/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

citiLeaf/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, only: [:cities]
	before_action :authenticate_business!, only: [:cities]
	protect_from_forgery with: :exception
end

citiLeaf/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def cities
  end
end

citiLeaf/app/helpers/application_helper.rb
module ApplicationHelper
end

citiLeaf/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

citiLeaf/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CitiLeaf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if business_signed_in? %>
      <li><%= link_to "Cities", cities_path %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_business_registration_path %></li>
      <li><%= link_to "Sign In", new_business_session_path %></li>
    <% end %>
    <% if user_signed_in? %>
      <li><%= link_to "Cities", cities_path %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
  	<ul>
		<li><%= link_to "Home", home_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Cities", cities_path %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
	</ul>
  	<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
  </body>
</html>

citiLeaf/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

citiLeaf/app/views/static_pages/cities.html.erb
<h1>StaticPages#cities</h1>
<p>Find me in app/views/static_pages/cities.html.erb</p>

citiLeaf/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>